import initScrollSuave from "./modules/scroll-suave.js";
import initAnimacaoScroll from "./modules/animacao-scroll.js";
import initAccordeonList from "./modules/accordeon-list.js";
import initNavTabs from "./modules/tab-nav.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initAnimacaoNumeros from "./modules/animacao-numeros.js";
import initFuncionamento from "./modules/funcionamento.js";

initScrollSuave();
initAnimacaoScroll();
initAccordeonList();
initNavTabs();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initAnimacaoNumeros();
initFuncionamento();
